// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/albums/album.proto

package albums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_albums_album_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{0}
}

func (x *Album) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Album) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumRequest) Reset() {
	*x = CreateAlbumRequest{}
	mi := &file_proto_albums_album_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumRequest) ProtoMessage() {}

func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlbumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsRequest) Reset() {
	*x = GetAlbumsRequest{}
	mi := &file_proto_albums_album_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsRequest) ProtoMessage() {}

func (x *GetAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{2}
}

type GetAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsResponse) Reset() {
	*x = GetAlbumsResponse{}
	mi := &file_proto_albums_album_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsResponse) ProtoMessage() {}

func (x *GetAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlbumsResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	mi := &file_proto_albums_album_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAlbumRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumResponse) Reset() {
	*x = DeleteAlbumResponse{}
	mi := &file_proto_albums_album_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumResponse) ProtoMessage() {}

func (x *DeleteAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAlbumResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_albums_album_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_albums_album_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_albums_album_proto_rawDescGZIP(), []int{6}
}

var File_proto_albums_album_proto protoreflect.FileDescriptor

const file_proto_albums_album_proto_rawDesc = "" +
	"\n" +
	"\x18proto/albums/album.proto\x12\n" +
	"mpm.albums\"l\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"J\n" +
	"\x12CreateAlbumRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x12\n" +
	"\x10GetAlbumsRequest\">\n" +
	"\x11GetAlbumsResponse\x12)\n" +
	"\x06albums\x18\x01 \x03(\v2\x11.mpm.albums.AlbumR\x06albums\"$\n" +
	"\x12DeleteAlbumRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13DeleteAlbumResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty2\xea\x01\n" +
	"\fAlbumService\x12@\n" +
	"\vCreateAlbum\x12\x1e.mpm.albums.CreateAlbumRequest\x1a\x11.mpm.albums.Album\x12H\n" +
	"\tGetAlbums\x12\x1c.mpm.albums.GetAlbumsRequest\x1a\x1d.mpm.albums.GetAlbumsResponse\x12N\n" +
	"\vDeleteAlbum\x12\x1e.mpm.albums.DeleteAlbumRequest\x1a\x1f.mpm.albums.DeleteAlbumResponseB\x0eZ\fproto/albumsb\x06proto3"

var (
	file_proto_albums_album_proto_rawDescOnce sync.Once
	file_proto_albums_album_proto_rawDescData []byte
)

func file_proto_albums_album_proto_rawDescGZIP() []byte {
	file_proto_albums_album_proto_rawDescOnce.Do(func() {
		file_proto_albums_album_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_albums_album_proto_rawDesc), len(file_proto_albums_album_proto_rawDesc)))
	})
	return file_proto_albums_album_proto_rawDescData
}

var file_proto_albums_album_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_albums_album_proto_goTypes = []any{
	(*Album)(nil),               // 0: mpm.albums.Album
	(*CreateAlbumRequest)(nil),  // 1: mpm.albums.CreateAlbumRequest
	(*GetAlbumsRequest)(nil),    // 2: mpm.albums.GetAlbumsRequest
	(*GetAlbumsResponse)(nil),   // 3: mpm.albums.GetAlbumsResponse
	(*DeleteAlbumRequest)(nil),  // 4: mpm.albums.DeleteAlbumRequest
	(*DeleteAlbumResponse)(nil), // 5: mpm.albums.DeleteAlbumResponse
	(*Empty)(nil),               // 6: mpm.albums.Empty
}
var file_proto_albums_album_proto_depIdxs = []int32{
	0, // 0: mpm.albums.GetAlbumsResponse.albums:type_name -> mpm.albums.Album
	1, // 1: mpm.albums.AlbumService.CreateAlbum:input_type -> mpm.albums.CreateAlbumRequest
	2, // 2: mpm.albums.AlbumService.GetAlbums:input_type -> mpm.albums.GetAlbumsRequest
	4, // 3: mpm.albums.AlbumService.DeleteAlbum:input_type -> mpm.albums.DeleteAlbumRequest
	0, // 4: mpm.albums.AlbumService.CreateAlbum:output_type -> mpm.albums.Album
	3, // 5: mpm.albums.AlbumService.GetAlbums:output_type -> mpm.albums.GetAlbumsResponse
	5, // 6: mpm.albums.AlbumService.DeleteAlbum:output_type -> mpm.albums.DeleteAlbumResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_albums_album_proto_init() }
func file_proto_albums_album_proto_init() {
	if File_proto_albums_album_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_albums_album_proto_rawDesc), len(file_proto_albums_album_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_albums_album_proto_goTypes,
		DependencyIndexes: file_proto_albums_album_proto_depIdxs,
		MessageInfos:      file_proto_albums_album_proto_msgTypes,
	}.Build()
	File_proto_albums_album_proto = out.File
	file_proto_albums_album_proto_goTypes = nil
	file_proto_albums_album_proto_depIdxs = nil
}
