version: '3.8'

services:
  mpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpm-app
    volumes:
      - mpm-data:/opt/mpm/data
    ports:
      - "8484:8484"
    restart: unless-stopped
    environment:
      - TZ=UTC

volumes:
  mpm-data:
  # Named volume for persistent data storage