version: '3.8'

services:
  mpm:
    image: ghcr.io/tyatyushkin/mpm:latest
    container_name: mpm
    volumes:
      - /opt/mpm/data:/opt/mpm/data
    ports:
      - "8484:8484"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGO_DATABASE=${MONGO_DATABASE:-mpm_db}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: mpm_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-changeMe123}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-mpm_db}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - /opt/mpm/mongo:/data/db

volumes:
  mpm-data:
  # Named volume for persistent data storage