name: Build and Deploy MPM

on:
  push:
    branches: [ homework6 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tyatyushkin
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./mpm
          push: true
          tags: ghcr.io/tyatyushkin/mpm:latest



#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          passphrase: ${{ secrets.SSH_PASSPHRASE }}
#          script: |
#            cd /path/to/deployment
#            docker pull ghcr.io/${{ github.repository_owner }}/mpm:latest
#            docker-compose down
#            echo "DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/mpm:latest" > .env
#            docker-compose up -d